### ISSUE TITLE
sile-strike is available, if you want it

### ISSUE THREAD

**Issue by ctrlcctrlv** [sile-typesetter/sile-packages#9]
This is kind of a "meh" package.

I plan to make a `sile-tabular`.

Now that should be more exciting.

https://github.com/ctrlcctrlv/sile-strike

**Comment by alerque** [comment]
Sure. PR for inclusion in the package directory.

By the way I'm thinking we should add a namespace prefix system to this directory to disambiguate. We're definitely going to run into collisions. I have a `strike` package I used in a couple projects too that's quite different. Not going to happen this instant, just be aware that might come later.

**Comment by ctrlcctrlv** [comment]
@alerque Cool beans, that's fine with me. I might do it like this instead:

```tex
\script[src=caleb/strike]
\script[src=fred/strike] % caleb's `strike` overwritten
\script[src=caleb/strike] % fred's `strike` overwritten
\script[src=fred/strike, _strike=fredstrike] % fred's strike is now `\fredstrike`, while caleb's remains `\strike`
```

But your idea is sure to be better. 😄

**Comment by alerque** [comment]
First, packages are handled differently now and I'm marking this repository as deprecated.

Second, the existing `rules` package gained much better metrics for calculating lengths of text nodes and now also provides underline, strikethrough, and even some boxing functions.
